version: "3"

services:
  db:
    image: postgres:11.5-alpine
    container_name: gamenews_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    restart: always
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: gamenews_web
    command: gunicorn display.wsgi:application --bind 0.0.0.0:8000 -w4
    volumes:
      - .:/usr/src/app/
    env_file: .env
    depends_on:
      - db
    links:
      - db
    restart: always

  nginx:
    build: ./nginx
    container_name: gamenews_nginx
    ports:
      - "8000:80"
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
    restart: always

volumes:
  postgres_data:
